name: Manning`s Blog
on: push

env:
  GH_USERNAME: toshaojin
  GH_EMAIL: toshaojin@gmail.com
  GH_REPO: github.com/toshaojin/toshaojin.github.io
  GH_BRANCH: master

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - name: Checkout
      uses: actions/checkout@master
      with:
          submodules: true
          fetch-depth: 1
    - name: Build site
      uses: jakejarvis/hugo-build-action@master
      with:
        args: --minify
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: site
        path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: alpine/git
    steps:
    - name: Download Artifact
      uses: actions/download-artifact@v2
      with:
        name: site
    - name: Setup git
      run: |
        git config --global user.name "${GH_USERNAME}"
        git config --global user.email "${GH_EMAIL}"
    - name: Deploy to GitHub
      run: |
        git init && git add .
        for try in $(seq 10); do
          git commit -m "Build By GitHub Actions on $(date "+%Y-%m-%d %T")"
          if git push -f "${{ secrets.ACTIONS_DEPLOY_KEY }}@${GH_REPO}" master:${GH_BRANCH}; then
            exit 0
          else
            sleep $(shuf -i 3-10 -n 1)
          fi
        done
        exit 1
