name: Manning`s Life 	#自动化的名称
on: 
  push: 	# push的时候触发工作流
    branches: 	#触发的分支 
      - master

jobs:	#开始工作流
  build:
    runs-on: ubuntu-latest	#使用Ubuntu镜像
    steps:
    - name: Checkout	#步骤名称
      uses: actions/checkout@master   #使用的软件名称和对应版本
      with:	#软件内指定的参数
          submodules: true
    - name: Setup Hugo	#安装Hugo
      uses: peaceiris/actions-hugo@v2.4.11
      with:
          hugo-version: 'latest'
          extended: true  
    - name: Build
      run: hugo --minify	#运行Hugo以生成静态网站文件
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}   #自动部署所需要的SSL KEY
          external_repository: toshaojin/toshaojin.github.io   #部署到指定`repository`
          publish_branch: master   #部署指定`repository`的分支
          publish_dir: ./public	   #需要部署的文件夹
          cname: shaojin.me     #部署之后希望重定向的域名
